# Generated by Django 4.2.7 on 2023-11-08 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_city', models.CharField(max_length=200)),
                ('developer', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('Reserved', models.BooleanField(default=None)),
                ('Sold', models.BooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='SoldHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(max_length=200, null=True)),
                ('commission_percent', models.CharField(max_length=200, null=True)),
                ('downpayment_amount', models.FloatField(default=0)),
                ('financing_option', models.CharField(max_length=200, null=True)),
                ('id_of_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.houselist')),
            ],
        ),
        migrations.CreateModel(
            name='LoanAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_loan', models.FloatField()),
                ('current_loan', models.FloatField()),
                ('id_of_house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='houses.houselist')),
            ],
        ),
    ]
