# Generated by Django 4.2.7 on 2023-11-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houselist',
            name='Reserved',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='houselist',
            name='Sold',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
