# Generated by Django 4.2.7 on 2023-11-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_alter_houselist_reserved_alter_houselist_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houselist',
            old_name='Reserved',
            new_name='reserved',
        ),
        migrations.RenameField(
            model_name='houselist',
            old_name='Sold',
            new_name='sold',
        ),
    ]
