# Generated by Django 4.2.7 on 2023-11-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_alter_houselist_reserved_alter_houselist_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldhouse',
            name='financing_option',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
