# Generated by Django 4.2.7 on 2023-11-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_alter_soldhouse_financing_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanamount',
            old_name='current_loan',
            new_name='current_amount',
        ),
        migrations.RenameField(
            model_name='loanamount',
            old_name='original_loan',
            new_name='original_amount',
        ),
    ]
